apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  volumes:
  - name: flask-app-vol
    configMap:
      name: flask-app-config
  containers:
  - image: nginx:alpine
    name: flask-app
    volumeMounts:
    - name: flask-app-vol
      mountPath: /etc/flask-app
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: flask-app