apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          proxy_pass http://flask-app:5000;
        }
      }
    }